# Generated by Django 3.1.3 on 2021-03-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('red1', models.CharField(blank=True, max_length=20)),
                ('red2', models.CharField(blank=True, max_length=20)),
                ('red3', models.CharField(blank=True, max_length=20)),
                ('red4', models.CharField(blank=True, max_length=20)),
                ('red5', models.CharField(blank=True, max_length=20)),
                ('red6', models.CharField(blank=True, max_length=20)),
                ('blue', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 't_history',
            },
        ),
    ]
